"""added quantity to discount model

Revision ID: 05e2030dfbe3
Revises: 64cbfdf2d8d1
Create Date: 2019-01-20 09:28:18.015000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e2030dfbe3'
down_revision = '64cbfdf2d8d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discount', sa.Column('qty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discount', 'qty')
    # ### end Alembic commands ###
