"""init tables

Revision ID: 84caedd23778
Revises: 
Create Date: 2019-01-19 18:17:57.505000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84caedd23778'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_food_id'), 'cost', ['food_id'], unique=False)
    op.create_index(op.f('ix_cost_vendor_id'), 'cost', ['vendor_id'], unique=False)
    op.create_table('discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('cost_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_cost_id'), 'discount', ['cost_id'], unique=False)
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hawker_centre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('unit_no', sa.String(length=20), nullable=True),
    sa.Column('hawker_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_hawker_id'), 'vendor', ['hawker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_hawker_id'), table_name='vendor')
    op.drop_table('vendor')
    op.drop_table('hawker_centre')
    op.drop_table('food')
    op.drop_index(op.f('ix_discount_cost_id'), table_name='discount')
    op.drop_table('discount')
    op.drop_index(op.f('ix_cost_hawker_id'), table_name='cost')
    op.drop_index(op.f('ix_cost_food_id'), table_name='cost')
    op.drop_table('cost')
    # ### end Alembic commands ###
